services:
  db:
    image: postgres:15-alpine
    container_name: jobboard_db
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: jobboard
      POSTGRES_PASSWORD: jobboard
    # Remove host port mapping to avoid conflicts
    # ports:
    #   - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobboard -d jobboard"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: jobboard_web
    command: /app/entrypoint.sh
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "*"
      USE_SQLITE: "0"
      POSTGRES_DB: jobboard
      POSTGRES_USER: jobboard
      POSTGRES_PASSWORD: jobboard
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:alpine
    container_name: jobboard_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  db_data:
